#!/bin/bash

set -euxo pipefail

export PRIVATE_CONFIG=${SNAP_USER_COMMON}/constellation/node.conf
GLOBAL_ARGS="--syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,net,shh,txpool,personal,web3,quorum,istanbul"

exec ${SNAP}/bin/geth --networkid "$(cat ${SNAP_USER_COMMON}/quorum/networkid)" --bootnodes "$(cat ${SNAP_USER_COMMON}/quorum/bootnodes)" --datadir ${SNAP_USER_COMMON}/ethereum ${GLOBAL_ARGS} "$@"
