name: quorum
version: 'master'
summary: A permissioned implementation of Ethereum supporting data privacy
description: |
  Quorum is an Ethereum-based distributed ledger protocol with transaction/contract privacy and new consensus mechanisms.

grade: stable
confinement: strict

apps:
  geth:
    command: bin/geth-wrapper
    plugs:
      - network
      - network-bind
      # hardware-observe is necessary when installing on actual hardware, or
      # geth will hang on init trying to enumerate usb devices. Even if --nousb
      # is specified. See https://github.com/ethereum/go-ethereum/issues/15101.
      - hardware-observe
  swarm:
    command: bin/swarm
    plugs:
      - network
      - network-bind
      - hardware-observe  # see above note on geth, same applies here
  bootnode:
    command: bin/bootnode
    plugs:
      - network
      - network-bind
      - hardware-observe  # see above note on geth, same applies here
  puppeth:
    command: bin/puppeth
    plugs:
      - network
      - network-bind
      - hardware-observe  # see above note on geth, same applies here
  constellation-node:
    command: bin/constellation-wrapper
    plugs:
      - network
      - network-bind
  constellation-config:
    command: bin/constellation-config.py
  init:
    command: bin/quorum-init.py
    plugs:
      - network
      - network-bind
      - hardware-observe
  attach:
    command: bin/attach.bash
    plugs:
      - network
      - network-bind
      - hardware-observe

parts:
  go:
    source-tag: go1.9.2
  quorum:
    after: [go]
    source: https://github.com/jpmorganchase/quorum.git
    source-branch: master
    plugin: nil
    build: |
        make geth swarm
        for c in bootnode puppeth; do
            build/env.sh go run build/ci.go install ./cmd/${c}
        done
    install: |
        mkdir -p $SNAPCRAFT_PART_INSTALL/bin
        for f in geth swarm bootnode puppeth; do
            mv build/bin/${f} $SNAPCRAFT_PART_INSTALL/bin
        done
    stage:
      - bin
  constellation:
    source: https://github.com/jpmorganchase/constellation.git
    source-tag: master
    plugin: nil
    build-packages:
      - libdb-dev
      - libleveldb-dev
      - libsodium-dev
      - zlib1g-dev
      - libtinfo-dev
    stage-packages:
      - libleveldb1v5
      - libsodium18
      - zlib1g
      - libtinfo5
    prepare: |
      if [ ! `command -v stack` ]; then
          curl -sSL https://get.haskellstack.org/ | sh -s - -f
          stack setup
      fi
    build: |
      stack install
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp .stack-work/install/x86_64-linux/lts-*/*/bin/constellation-node $SNAPCRAFT_PART_INSTALL/bin
    stage:
      - bin/constellation-node
      - lib
      - usr/lib
  wrappers-and-scripts:
    source: .
    plugin: nil
    stage-packages:
      - python3-jinja2
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      for s in constellation-config.py constellation-wrapper geth-wrapper quorum-init.py attach.bash; do
        cp ../../../snap/${s} $SNAPCRAFT_PART_INSTALL/bin
      done
    stage:
      - bin
      - usr/lib
